apiVersion: v1
kind: Pod
spec:
  containers:
  - name: nodejs
    image: node:22
    command:
    - cat
    tty: true  
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=/workspace/Dockerfile"
    - "--context=/workspace"
    - "--destination=docker.io/anas1243/solar-app:latest"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
    - name: workspace-volume
      mountPath: /workspace  
  volumes:
  - name: kaniko-secret
    secret:
      secretName: kaniko-secret  